# -*- coding: utf-8 -*-
"""sepsis on BERT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17u3RLFX7vXdtawRicmTDCsUJnIhaqGzt
"""

!pip install transformers datasets accelerate scikit-learn pandas numpy

# ===============================
# IMPORT LIBRARIES
# ===============================

import pandas as pd
import numpy as np
import torch

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

from transformers import (
    BertTokenizer,
    BertForSequenceClassification,
    Trainer,
    TrainingArguments
)

from datasets import Dataset

# ===============================
# LOAD DATASET
# ===============================

# PUT YOUR DATASET PATH HERE
dataset_path = "/content/sepsis_data.csv"

df = pd.read_csv(dataset_path)

df.head()

# Fill missing values using forward fill (time-series friendly)
df = df.fillna(method="ffill")

# If still missing
df = df.fillna(0)

# ===============================
# CONVERT TO TEXT FORMAT FOR BERT
# ===============================

def convert_to_text(row):
    return f"""
    Heart rate {row['HR']}
    Blood pressure {row['MAP']}
    Temperature {row['Temp']}
    WBC {row['WBC']}
    Lactate {row['Lactate']}
    """

df["text"] = df.apply(convert_to_text, axis=1)

df["label"] = df["SepsisLabel"]

# train test split
from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    stratify=df["label"],
    random_state=42
)

import os

# folder structure
os.makedirs("/content/sepsis_data/train", exist_ok=True)
os.makedirs("/content/sepsis_data/test", exist_ok=True)

train_df.to_csv("/content/sepsis_data/train/train.csv", index=False)
test_df.to_csv("/content/sepsis_data/test/test.csv", index=False)

print("Files saved successfully!")

# Verify Files Exist
!ls /content/sepsis_data/train
!ls /content/sepsis_data/test

# ===============================
# LOAD PRETRAINED BERT
# ===============================

model_name = "bert-base-uncased"

tokenizer = BertTokenizer.from_pretrained(model_name)


model = BertForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2,
    problem_type="single_label_classification"
)

# Tokenize text

train_encodings = tokenizer(
    list(train_df["text"]),
    truncation=True,
    padding=True,
    max_length=128
)

val_encodings = tokenizer(
    list(test_df["text"]),
    truncation=True,
    padding=True,
    max_length=128
)

# Convert to HuggingFace Dataset
import torch # Ensure torch is imported for tensor conversion

train_dataset = Dataset.from_dict({
    "input_ids": train_encodings["input_ids"],
    "attention_mask": train_encodings["attention_mask"],
    "labels": torch.tensor(train_df["label"].values, dtype=torch.long) # Explicitly cast to torch.long
})

val_dataset = Dataset.from_dict({
    "input_ids": val_encodings["input_ids"],
    "attention_mask": val_encodings["attention_mask"],
    "labels": torch.tensor(test_df["label"].values, dtype=torch.long) # Explicitly cast to torch.long
})

# Handle Class Imbalance (Important for Sepsis)

# Sepsis datasets are highly imbalanced

from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(df["label"]),
    y=df["label"]
)

class_weights = torch.tensor(class_weights, dtype=torch.float)

# define metrics
def compute_metrics(eval_pred):

    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average='binary'
    )

    acc = accuracy_score(labels, predictions)

    return {
        "accuracy": acc,
        "f1": f1,
        "precision": precision,
        "recall": recall
    }

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",

    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,

    num_train_epochs=3,

    # evaluation_strategy=IntervalStrategy.EPOCH, # Removed due to TypeError
    # save_strategy=SaveStrategy.EPOCH,       # Removed due to TypeError

    logging_dir="./logs"

    # load_best_model_at_end=True             # Removed due to TypeError
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    compute_metrics=compute_metrics
)

# This step:

# Downloads pretrained BERT
# Fine-tunes on ICU data
# Adjusts weights
# Learns sepsis patterns
trainer.train()

# evaluation
trainer.evaluate()

# Save Fine-Tuned Model
trainer.save_model("Sepsis_BERT_Model")
tokenizer.save_pretrained("Sepsis_BERT_Model")

# load save model later
from transformers import BertForSequenceClassification

model = BertForSequenceClassification.from_pretrained("Sepsis_BERT_Model")

# predict sepsis (early warning)
text = """
Heart rate 120
Blood pressure 85
Temperature 39
WBC 16
Lactate 3.2
"""

inputs = tokenizer(text, return_tensors="pt")

outputs = model(**inputs)

pred = torch.argmax(outputs.logits)

print("Sepsis Prediction:", pred.item())